version: '3.7'
services:
    postgres:
        image: postgis/postgis:14-3.4
        restart: always
        env_file:
          - .env
        ports:
          - '5433:5432'
        volumes:
          - postgres:/var/lib/postgresql/data
#          - ./sql/add_postgis_ext.sql:/docker-entrypoint-initdb.d/add_postgis_ext.sql
    plotter-rest_api:
        build:
          context: .
          target: start_app
        ports:
          - "8080:8080"
        volumes:
        - ./:/usr/src/app
        depends_on:
          - postgres
        env_file:
          - .env
volumes:
  postgres:


# docker-compose run web alembic revision --autogenerate -m "First migration"

# docker-compose run web alembic upgrade head